### ISSUE TITLE
How about single sha256 speed?

### ISSUE THREAD

**Issue by hskun** [zhaohaixu/SHA256-FPGA-HLS#1]
How about single sha256 speed?
I think the bandwidth maybe not very high.

**Comment by zhaohaixu** [comment]
Sorry for neglecting your issue due to the lack of maintenance for a long time. A single kernel execution takes about 0.1 milliseconds. When I first started HLS, I only paid attention to the pipeline and dataflow. I am ashamed that I did not consider the problem of bandwidth in the design.
